name: mdns-repeater

services:
  mdns-repeater:
    image: angelnu/mdns_repeater:latest
    container_name: mdns-repeater
    restart: unless-stopped
    network_mode: host
    environment:
      options: br1
      hostNIC: vlan1
      dockerNIC: vlan4
