name: homeassistant

services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    privileged: true
    environment:
      TZ: America/Chicago
      DB_URL: postgresql://${HA_DB_USERNAME}:${HA_DB_PASSWORD}@homeassistant-postgres/homeassistant
    volumes:
      - /mnt/storage/appdata/homeassistant:/config
    networks:
      internal:
      vlan1:
        ipv4_address: 172.27.137.5
        mac_address: "02:42:ac:1b:89:05"
      vlan4:
        ipv4_address: 192.168.75.2
        mac_address: "02:42:c0:a8:4b:02"
      proxy:
      monitoring:
    depends_on:
      homeassistant-postgres:
        condition: service_healthy
    healthcheck:
      test: curl -f http://localhost:8123/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  homeassistant-postgres:
    image: postgres:18
    container_name: homeassistant-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${HA_DB_USERNAME}
      POSTGRES_PASSWORD: ${HA_DB_PASSWORD}
      POSTGRES_DB: homeassistant
    volumes:
      - /mnt/storage/appdata/postgres/homeassistant:/var/lib/postgresql
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c track_activity_query_size=4096
    networks:
      - internal
      - monitoring
    healthcheck:
      test: pg_isready --dbname=${POSTGRES_DB} --username=${POSTGRES_USER}
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  matter-server:
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    container_name: matter-server
    restart: unless-stopped
    volumes:
      - /mnt/storage/appdata/matter-server:/data
    networks:
      internal:
      vlan1:
        ipv4_address: 172.27.137.6
        mac_address: "02:42:ac:1b:89:06"
      vlan4:
        ipv4_address: 192.168.75.3
        mac_address: "02:42:c0:a8:4b:03"

networks:
  internal:
  vlan1:
    name: homeassistant-vlan1
    driver: macvlan
    driver_opts:
      parent: vlan1
    ipam:
      config:
        - subnet: 172.27.137.0/24
          gateway: 172.27.137.1
          ip_range: 172.27.137.4/30
  vlan4:
    name: homeassistant-vlan4
    driver: macvlan
    driver_opts:
      parent: vlan4
    ipam:
      config:
        - subnet: 192.168.75.0/24
          gateway: 192.168.75.1
          ip_range: 192.168.75.0/30
  proxy:
    name: proxy
    external: true
  monitoring:
    name: monitoring
    external: true
