DD_API_KEY='{{ op://NAS/Datadog agent API key/credential }}'
TESLAMATE_POSTGRES_USER='{{ op://NAS/TeslaMate DB datadog/username }}'
TESLAMATE_POSTGRES_PASSWORD='{{ op://NAS/TeslaMate DB datadog/password }}'
IMMICH_POSTGRES_USER='{{ op://NAS/Immich DB datadog/username }}'
IMMICH_POSTGRES_PASSWORD='{{ op://NAS/Immich DB datadog/password }}'
SNMP_AUTH_KEY='{{ op://NAS/TrueNAS SNMP/auth_key }}'
SNMP_PRIV_KEY='{{ op://NAS/TrueNAS SNMP/priv_key }}'
